name: Deploy to cPanel

on:
  push:
    branches:
      - main # Or your preferred branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to cPanel via SSH
      run: |
        ssh bettered@https://betteredgestechnologies.com.ng "cd /public_html/ascend && git pull origin main && composer install --no-dev --prefer-dist && php artisan migrate --force && php artisan config:cache && php artisan route:cache"
      env:
        SSH_KNOWN_HOSTS: https://betteredgestechnologies.com.ng 